baseUrl: http://localhost
services:
  user-management:
    port: 3000
    docsUrl: api-docs/users
  swagger-service:
    port: 3001
    docsUrl: api-docs
  dictionary-service:
    port: 3002
    docsUrl: api-docs/dictionary
