baseUrl: http://localhost
services:
  user-manager:
    port: 3000
    docsUrl: api-docs/users
  swagger-manager:
    port: 3010
    docsUrl: api-docs
  wordset-manager:
    port: 3020
    docsUrl: api-docs/wodrset-management
  lingualeo-api-manager:
    port: 3030
    docsUrl: api-docs/lingualeo-api
